version: '3'  # version of compose format 
services:
  time_calc-service:
    build: ./DockerMongo  
    volumes:
    - ./DockerMongo:/usr/src/app 
    ports:
      - 5001:80  # host:container
    links:
      - db
  db:
    image: mongo:3.0.2
    command: --smallfiles
    ports:
      - "27017:27017"
  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - time_calc-service  # website is not going to work unless laptop-service is running
